#!/bin/sh

#gpgme, xml::simple

#SUNWgnugetopt
#SUNWmm-common
#cairo-bcop

pfexec pkg install -Iv \
pkg:/SUNWcs \
pkg:/archiver/gnu-tar \
pkg:/codec/flac \
pkg:/codec/libtheora \
pkg:/codec/ogg-vorbis \
pkg:/codec/speex \
pkg:/communication/conferencing/ekiga \
pkg:/communication/pda/pilot-link \
pkg:/compatibility/packages/SUNWxwinc \
pkg:/compatibility/packages/SUNWxwplr \
pkg:/compatibility/packages/SUNWxwplt \
pkg:/compress/bzip2 \
pkg:/compress/unzip \
pkg:/compress/zip \
pkg:/crypto/gnupg \
pkg:/data/docbook \
pkg:/data/iso-codes \
pkg:/database/mysql-51 \
pkg:/database/mysql-51/library \
pkg:/database/sqlite-3 \
pkg:/database/sqlite-3/documentation \
pkg:/desktop/archive-manager/file-roller \
pkg:/desktop/calculator/gcalctool \
pkg:/desktop/cd-burning/brasero \
pkg:/desktop/character-map/gucharmap \
pkg:/desktop/compiz \
pkg:/desktop/compiz/library/compizconfig-gconf \
pkg:/desktop/compiz/library/libcompizconfig \
pkg:/desktop/compiz/plugin/compiz-fusion-extra \
pkg:/desktop/compiz/plugin/compiz-fusion-main \
pkg:/desktop/gksu \
pkg:/desktop/media-player/moovida \
pkg:/desktop/media-player/moovida/moovida-plugins \
pkg:/desktop/pdf-viewer/evince \
pkg:/desktop/remote-desktop/rdesktop \
pkg:/desktop/remote-desktop/tigervnc \
pkg:/desktop/xdg/xdg-user-dirs-gtk \
pkg:/desktop/xdg/xdg-utils \
pkg:/desktop/xscreensaver \
pkg:/desktop/xscreensaver/hacks \
pkg:/desktop/xscreensaver/hacks/hacks-gl \
pkg:/developer/build/ant \
pkg:/developer/build/automake-110 \
pkg:/developer/build/cmake \
pkg:/developer/build/gnu-make \
pkg:/developer/build/libtool \
pkg:/developer/documentation-tool/gtk-doc \
pkg:/developer/documentation-tool/openjade \
pkg:/developer/documentation-tool/opensp \
pkg:/developer/gcc-3 \
pkg:/developer/gnome/gettext \
pkg:/developer/gnome/gnome-doc-utils \
pkg:/developer/gnu-binutils \
pkg:/developer/gperf \
pkg:/developer/java/jdk \
pkg:/developer/library/lint \
pkg:/developer/linker \
pkg:/developer/macro/gnu-m4 \
pkg:/developer/object-file \
pkg:/developer/parser/antlr-2 \
pkg:/developer/parser/bison \
pkg:/developer/ui-designer/glade \
pkg:/developer/vala \
pkg:/developer/xopen/xcu4 \
pkg:/driver/storage/arcmsr \
pkg:/driver/usb/ugen \
pkg:/editor/gedit \
pkg:/editor/ghex \
pkg:/file/gnu-coreutils \
pkg:/file/gnu-findutils \
pkg:/gnome/accessibility/gnome-a11y-libs \
pkg:/gnome/accessibility/gok \
pkg:/gnome/applet/gnome-applets \
pkg:/gnome/applet/gnome-fun-applets \
pkg:/gnome/applet/gnome-intranet-applets \
pkg:/gnome/applet/gnome-mm-applets \
pkg:/gnome/applet/gnome-utility-applets \
pkg:/gnome/config/gconf \
pkg:/gnome/config/gconf/gconf-editor \
pkg:/gnome/desklet/gdesklets \
pkg:/gnome/desklet/gdesklets-extra \
pkg:/gnome/disk-analyzer/baobab \
pkg:/gnome/file-manager/nautilus \
pkg:/gnome/gnome-audio \
pkg:/gnome/gnome-camera \
pkg:/gnome/gnome-dictionary \
pkg:/gnome/gnome-keyring \
pkg:/gnome/gnome-log-viewer \
pkg:/gnome/gnome-panel \
pkg:/gnome/gnome-screenshot \
pkg:/gnome/gnome-search-tool \
pkg:/gnome/gnome-session \
pkg:/gnome/help-viewer/yelp \
pkg:/gnome/media/gnome-media \
pkg:/gnome/media/gnome-media-player \
pkg:/gnome/media/sound-recorder \
pkg:/gnome/preferences/control-center \
pkg:/gnome/security/seahorse \
pkg:/gnome/security/seahorse/seahorse-plugins \
pkg:/gnome/speech/gnome-speech \
pkg:/gnome/speech/gnome-speech/driver/gnome-speech-espeak \
pkg:/gnome/theme/blueprint \
pkg:/gnome/theme/cursor/dmz-cursor \
pkg:/gnome/theme/cursor/dmz-cursor-aa \
pkg:/gnome/theme/gnome-icon-theme \
pkg:/gnome/theme/gnome-themes \
pkg:/gnome/theme/gnome-themes-extra \
pkg:/gnome/theme/gtk2-engines \
pkg:/gnome/theme/gtk2-engines-extra \
pkg:/gnome/theme/hicolor-icon-theme \
pkg:/gnome/theme/nimbus \
pkg:/gnome/theme/nimbus-hires \
pkg:/gnome/theme/sound/xdg-sound-theme \
pkg:/gnome/theme/tango-icon-theme \
pkg:/gnome/trusted/libgnometsol \
pkg:/gnome/window-manager/metacity \
pkg:/gnome/zenity \
pkg:/image/editor/gimp \
pkg:/image/editor/gimp/gimp-help \
pkg:/image/editor/gimp/locale/cs \
pkg:/image/editor/gimp/locale/de \
pkg:/image/editor/gimp/locale/es \
pkg:/image/editor/gimp/locale/extra \
pkg:/image/editor/gimp/locale/fr \
pkg:/image/editor/gimp/locale/it \
pkg:/image/editor/gimp/locale/ko \
pkg:/image/editor/gimp/locale/pl \
pkg:/image/editor/gimp/locale/ru \
pkg:/image/editor/gimp/locale/sv \
pkg:/image/editor/gimp/locale/zh_cn \
pkg:/image/editor/gimp/plugin/gimp-gtkam \
pkg:/image/gnome-backgrounds \
pkg:/image/imagemagick \
pkg:/image/library/babl \
pkg:/image/library/gegl \
pkg:/image/library/libart \
pkg:/image/library/libexif \
pkg:/image/library/libjpeg \
pkg:/image/library/libpng \
pkg:/image/library/librsvg \
pkg:/image/library/libtiff \
pkg:/image/scanner/xsane/sane-backends \
pkg:/image/viewer/eog \
pkg:/image/viewer/gthumb \
pkg:/image/webcam/cheese \
pkg:/library/aalib \
pkg:/library/audio/gstreamer \
pkg:/library/audio/gstreamer/plugin/gnonlin \
pkg:/library/audio/libmikmod \
pkg:/library/c++/glibmm \
pkg:/library/c++/libxml++ \
pkg:/library/c++/net6 \
pkg:/library/c++/obby \
pkg:/library/c++/sigcpp \
pkg:/library/desktop/atk \
pkg:/library/desktop/c++/cairomm \
pkg:/library/desktop/c++/gtkmm \
pkg:/library/desktop/c++/pangomm \
pkg:/library/desktop/cairo \
pkg:/library/desktop/clutter \
pkg:/library/desktop/clutter/clutter-gst \
pkg:/library/desktop/clutter/clutter-gtk \
pkg:/library/desktop/evolution-data-server \
pkg:/library/desktop/gobject/gir-repository \
pkg:/library/desktop/gobject/gobject-introspection \
pkg:/library/desktop/gtk-vnc \
pkg:/library/desktop/gtk2 \
pkg:/library/desktop/gtk2/gtk-backend-cups \
pkg:/library/desktop/gtk2/gtk-backend-papi \
pkg:/library/desktop/gtkhtml \
pkg:/library/desktop/gtksourceview \
pkg:/library/desktop/gtkspell \
pkg:/library/desktop/libchamplain \
pkg:/library/desktop/libgdata \
pkg:/library/desktop/libglade \
pkg:/library/desktop/libgnomecanvas \
pkg:/library/desktop/libgsf \
pkg:/library/desktop/libgweather \
pkg:/library/desktop/libsexy \
pkg:/library/desktop/libvisual \
pkg:/library/desktop/pango \
pkg:/library/desktop/pigment \
pkg:/library/desktop/search/tracker \
pkg:/library/desktop/xdg/icon-naming-utils \
pkg:/library/desktop/xdg/libcanberra \
pkg:/library/expat \
pkg:/library/file-monitor/gamin \
pkg:/library/gc \
pkg:/library/glib2 \
pkg:/library/gmime \
pkg:/library/gnome/base-libs \
pkg:/library/gnome/gnome-component \
pkg:/library/gnome/gnome-keyring \
pkg:/library/gnome/gnome-libs \
pkg:/library/gnome/gnome-vfs \
pkg:/library/gnome/print/gnome-print \
pkg:/library/gnome/print/gnome-print/gnome-print-papi \
pkg:/library/gnutls \
pkg:/library/graphics/libmng \
pkg:/library/graphics/pixman \
pkg:/library/idnkit \
pkg:/library/idnkit/header-idnkit \
pkg:/library/java/java-gnome \
pkg:/library/java/java-gnome/java-libgconf \
pkg:/library/java/java-gnome/java-libvte \
pkg:/library/lcms \
pkg:/library/libcroco \
pkg:/library/libdaemon \
pkg:/library/libffi \
pkg:/library/libgtop \
pkg:/library/libical \
pkg:/library/libidn \
pkg:/library/libmemcached \
pkg:/library/libnotify \
pkg:/library/liboil \
pkg:/library/libproxy \
pkg:/library/libproxy/libproxy-gnome \
pkg:/library/libproxy/libproxy-mozjs \
pkg:/library/libsoup \
pkg:/library/libtasn1 \
pkg:/library/libtool/libltdl \
pkg:/library/libunique \
pkg:/library/libxml2 \
pkg:/library/libxslt \
pkg:/library/media-player/totem-pl-parser \
pkg:/library/medialib \
pkg:/library/motif \
pkg:/library/musicbrainz/libdiscid \
pkg:/library/musicbrainz/libmusicbrainz \
pkg:/library/ncurses \
pkg:/library/neon \
pkg:/library/nspr \
pkg:/library/nspr/header-nspr \
pkg:/library/openldap \
pkg:/library/pcre \
pkg:/library/perl-5/authen-pam \
pkg:/library/perl-5/xml-parser \
pkg:/library/popt \
pkg:/library/print/cups-libs \
pkg:/library/print/open-printing \
pkg:/library/pth \
pkg:/library/python-2/cssutils-26 \
pkg:/library/python-2/ipython-26 \
pkg:/library/python-2/libxml2-24 \
pkg:/library/python-2/libxml2-26 \
pkg:/library/python-2/libxsl-24 \
pkg:/library/python-2/libxsl-26 \
pkg:/library/python-2/pyatspi-26 \
pkg:/library/python-2/pycups \
pkg:/library/python-2/pyopenssl-26 \
pkg:/library/python-2/python-compizconfig-26 \
pkg:/library/python-2/python-dbus-24 \
pkg:/library/python-2/python-dbus-26 \
pkg:/library/python-2/python-extra-24 \
pkg:/library/python-2/python-extra-26 \
pkg:/library/python-2/python-gnome-desktop-24 \
pkg:/library/python-2/python-gnome-extras-26 \
pkg:/library/python-2/python-gnome-libs-24 \
pkg:/library/python-2/python-gst-26 \
pkg:/library/python-2/python-gtk-vnc-24 \
pkg:/library/python-2/python-gtk-vnc-26 \
pkg:/library/python-2/python-imaging-26 \
pkg:/library/python-2/python-notify-26 \
pkg:/library/python-2/python-pigment-26 \
pkg:/library/python-2/python-twisted-24 \
pkg:/library/python-2/python-twisted-26 \
pkg:/library/python-2/python-twisted-web2-24 \
pkg:/library/python-2/python-twisted-web2-26 \
pkg:/library/python-2/python-xdg-26 \
pkg:/library/python-2/python-zope-interface-24 \
pkg:/library/python-2/python-zope-interface-26 \
pkg:/library/python-2/setuptools-24 \
pkg:/library/python-2/setuptools-26 \
pkg:/library/python-2/simplejson-26 \
pkg:/library/raptor \
pkg:/library/readline \
pkg:/library/samba/libsmbclient \
pkg:/library/sdl \
pkg:/library/security/libgpg-error \
pkg:/library/security/openssl \
pkg:/library/security/pam/module/pam-consolekit \
pkg:/library/slang \
pkg:/library/speech/espeak \
pkg:/library/spell-checking/enchant \
pkg:/library/tooltalk \
pkg:/library/xdg/consolekit \
pkg:/library/xdg/xdg-user-dirs \
pkg:/library/zlib \
pkg:/mail/evolution \
pkg:/mail/evolution/connector/evolution-exchange \
pkg:/mail/evolution/connector/evolution-webcal \
pkg:/mail/procmail \
pkg:/mail/thunderbird \
pkg:/mail/thunderbird/locale/de \
pkg:/mail/thunderbird/locale/es \
pkg:/mail/thunderbird/locale/extra \
pkg:/mail/thunderbird/locale/fr \
pkg:/mail/thunderbird/locale/it \
pkg:/mail/thunderbird/locale/ja \
pkg:/mail/thunderbird/locale/ko \
pkg:/mail/thunderbird/locale/pl \
pkg:/mail/thunderbird/locale/pt_br \
pkg:/mail/thunderbird/locale/ru \
pkg:/mail/thunderbird/locale/sv \
pkg:/mail/thunderbird/locale/zh_cn \
pkg:/mail/thunderbird/locale/zh_tw \
pkg:/mail/thunderbird/plugin/thunderbird-lightning \
pkg:/media/cdrtools \
pkg:/network/ssh/ssh-key \
pkg:/package/svr4 \
pkg:/print/cups \
pkg:/print/cups/hal-cups-utils \
pkg:/print/filter/ghostscript \
pkg:/print/lp/compatibility/sunos4 \
pkg:/print/lp/print-client-commands \
pkg:/print/lp/print-manager \
pkg:/release/name \
pkg:/runtime/java \
pkg:/runtime/java/runtime64 \
pkg:/runtime/lua \
pkg:/runtime/python-24 \
pkg:/runtime/python-25 \
pkg:/runtime/python-26 \
pkg:/runtime/tcl-8 \
pkg:/runtime/tcl-8/tcl-sqlite-3 \
pkg:/runtime/tk-8 \
pkg:/service/gnome/desktop-cache \
pkg:/service/hal \
pkg:/service/network/dns/mdns \
pkg:/service/network/samba \
pkg:/service/network/smtp/sendmail \
pkg:/service/postrun \
pkg:/service/security/gss \
pkg:/service/security/kerberos-5 \
pkg:/shell/bash \
pkg:/storage/fsexam \
pkg:/system/display-manager/desktop-startup \
pkg:/system/extended-system-utilities \
pkg:/system/file-system/ntfsprogs \
pkg:/system/file-system/zfs \
pkg:/system/header \
pkg:/system/header/header-audio \
pkg:/system/header/header-ugen \
pkg:/system/input-method/iiim \
pkg:/system/input-method/iiim/anthy \
pkg:/system/input-method/iiim/cle-core \
pkg:/system/input-method/iiim/cle-open \
pkg:/system/input-method/iiim/cle-sunpinyin \
pkg:/system/input-method/iiim/hangul \
pkg:/system/input-method/iiim/hkle-core \
pkg:/system/input-method/iiim/hkle-open \
pkg:/system/input-method/iiim/thaile \
pkg:/system/input-method/iiim/twle-chewing \
pkg:/system/input-method/iiim/twle-core \
pkg:/system/input-method/iiim/twle-open \
pkg:/system/kernel/security/gss \
pkg:/system/library \
pkg:/system/library/c++/sunpro \
pkg:/system/library/dbus \
pkg:/system/library/fontconfig \
pkg:/system/library/freetype-2 \
pkg:/system/library/gcc-3-runtime \
pkg:/system/library/iconv/unicode \
pkg:/system/library/iconv/utf-8 \
pkg:/system/library/libdbus \
pkg:/system/library/libdbus-glib \
pkg:/system/library/libvirt \
pkg:/system/library/math \
pkg:/system/library/math/header-math \
pkg:/system/library/mozilla-nss \
pkg:/system/library/mozilla-nss/header-nss \
pkg:/system/library/policykit \
pkg:/system/library/security/gss \
pkg:/system/library/security/gss/diffie-hellman \
pkg:/system/library/security/libgcrypt \
pkg:/system/library/security/libmcrypt \
pkg:/system/library/security/libsasl \
pkg:/system/library/usb/libusb \
pkg:/system/library/usb/libusbugen \
pkg:/system/management/product-registry \
pkg:/system/manual/locale/ca \
pkg:/system/manual/locale/ja \
pkg:/system/mozilla-nss \
pkg:/system/network/avahi \
pkg:/system/storage/parted \
pkg:/system/trusted \
pkg:/system/virtinst \
pkg:/system/xopen/xcu4 \
pkg:/system/zones \
pkg:/terminal/gnome-terminal \
pkg:/text/auto_ef \
pkg:/text/gawk \
pkg:/text/gnu-gettext \
pkg:/text/gnu-grep \
pkg:/text/gnu-patch \
pkg:/text/gnu-sed \
pkg:/web/browser/firefox \
pkg:/web/browser/firefox/locale/de_de \
pkg:/web/browser/firefox/locale/es_es \
pkg:/web/browser/firefox/locale/extra \
pkg:/web/browser/firefox/locale/fr_fr \
pkg:/web/browser/firefox/locale/hi_in \
pkg:/web/browser/firefox/locale/it_it \
pkg:/web/browser/firefox/locale/ja_jp \
pkg:/web/browser/firefox/locale/ko_kr \
pkg:/web/browser/firefox/locale/pl_pl \
pkg:/web/browser/firefox/locale/pt_br \
pkg:/web/browser/firefox/locale/ru_ru \
pkg:/web/browser/firefox/locale/sv_se \
pkg:/web/browser/firefox/locale/zh_cn \
pkg:/web/browser/firefox/locale/zh_tw \
pkg:/web/browser/w3m \
pkg:/web/curl \
pkg:/web/data/firefox-bookmarks \
pkg:/web/proxy/privoxy \
pkg:/web/urlgrabber \
pkg:/x11/compatibility/links-svid \
pkg:/x11/keyboard/data-xkb \
pkg:/x11/library/libice \
pkg:/x11/library/libxft \
pkg:/x11/library/mesa \
pkg:/x11/server/xorg \
pkg:/web/wget \
pkg:/compatibility/ucb \
pkg:/developer/icu \
pkg:/library/liblouis

exit 0
pkg:/library/python-2/python-gnome-desktop-26 \
pkg:/library/python-2/python-gnome-libs-26 \
