#
# Default IPS Meta actions and dependencies for GNOME packages on Solaris
#
# Copyright (c) 2010, 2011 Oracle and/or its affiliates. All rights reserved.
#

Meta(org.opensolaris.consolidation): desktop
Requires: consolidation/desktop/gnome-incorporation = *

# ChangeLog:
# 2011-01-19  Laszlo (Laca) Peter  <laszlo.peter@oracle.com>
# - move variant.opensolaris.zone to Solaris.inc
# 2010-06-10  Michal Pryc  <Michal.Pryc@Oracle.Com>
# - created
